USE Backshop_DEV
GO

UPDATE tblzCdNOICatPropType SET InactiveSw = 0, TemplateSw = 0, 
		AuditUpdateDate = GETDATE(), AuditUpdateUserId = 'GNARAYAN'
	WHERE PropertyTypeMajorCd_F IN (
		'IND',
		'OFF',
		'MIX',
		'RET',
		'OTH'
		)
GO

UPDATE tblzCdNOICategory SET OrderKey = 10 WHERE NOICategoryCd =  'ISR'
UPDATE tblzCdNOICategory SET OrderKey = 20 WHERE NOICategoryCd =  'VCL'
UPDATE tblzCdNOICategory SET OrderKey = 25 WHERE NOICategoryCd =  'ICA'
UPDATE tblzCdNOICategory SET OrderKey = 30 WHERE NOICategoryCd =  'LFE'
UPDATE tblzCdNOICategory SET OrderKey = 40 WHERE NOICategoryCd =  'IPK'
UPDATE tblzCdNOICategory SET OrderKey = 50 WHERE NOICategoryCd =  'OIV'
UPDATE tblzCdNOICategory SET OrderKey = 60 WHERE NOICategoryCd =  'IUA'
UPDATE tblzCdNOICategory SET OrderKey = 65 WHERE NOICategoryCd =  'IPR'
UPDATE tblzCdNOICategory SET OrderKey = 190 WHERE NOICategoryCd =  'RET'
UPDATE tblzCdNOICategory SET OrderKey = 180 WHERE NOICategoryCd =  'OIN'
UPDATE tblzCdNOICategory SET OrderKey = 120 WHERE NOICategoryCd =  'OUT'
UPDATE tblzCdNOICategory SET OrderKey = 170 WHERE NOICategoryCd =  'ORM'
UPDATE tblzCdNOICategory SET OrderKey = 110 WHERE NOICategoryCd =  'OPY'
UPDATE tblzCdNOICategory SET OrderKey = 150 WHERE NOICategoryCd =  'SC4'
UPDATE tblzCdNOICategory SET OrderKey = 90 WHERE NOICategoryCd =  'OMF'
UPDATE tblzCdNOICategory SET OrderKey = 100 WHERE NOICategoryCd =  'OGA'
UPDATE tblzCdNOICategory SET OrderKey = 200 WHERE NOICategoryCd =  'MLE'
UPDATE tblzCdNOICategory SET OrderKey = 210 WHERE NOICategoryCd =  'CRS'
UPDATE tblzCdNOICategory SET OrderKey = 220 WHERE NOICategoryCd =  'CEO'
UPDATE tblzCdNOICategory SET OrderKey = 230 WHERE NOICategoryCd =  'CTI'
UPDATE tblzCdNOICategory SET OrderKey = 240 WHERE NOICategoryCd =  'CCO'
GO

INSERT INTO tblzCdNOICatPropType (NOICategoryCd_F, PropertyTypeMajorCd_F, UseOnRentRollSw, OrderKey, TemplateSW, AuditAddDate, AuditAddUserId, AuditUpdateDate, AuditUpdateUserId) VALUES
	('ISR','IND',0,10,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ISR','OFF',0,10,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ISR','MIX',0,10,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ISR','RET',0,10,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ISR','OTH',0,10,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('VCL','IND',0,20,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('VCL','OFF',0,20,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('VCL','MIX',0,20,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('VCL','RET',0,20,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('VCL','OTH',0,20,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('ICA','IND',0,25,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ICA','OFF',0,25,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ICA','MIX',0,25,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ICA','RET',0,25,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ICA','OTH',0,25,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('LFE','IND',0,30,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('LFE','OFF',0,30,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('LFE','MIX',0,30,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('LFE','RET',0,30,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('LFE','OTH',0,30,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('IPK','IND',0,40,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPK','OFF',0,40,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPK','MIX',0,40,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPK','RET',0,40,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPK','OTH',0,40,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('OIV','IND',0,50,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIV','OFF',0,50,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIV','MIX',0,50,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIV','RET',0,50,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIV','OTH',0,50,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('IUA','IND',0,60,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IUA','OFF',0,60,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IUA','MIX',0,60,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IUA','RET',0,60,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IUA','OTH',0,60,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('IPR','IND',0,65,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPR','OFF',0,65,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPR','MIX',0,65,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPR','RET',0,65,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('IPR','OTH',0,65,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('RET','IND',0,190,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('RET','OFF',0,190,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('RET','MIX',0,190,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('RET','RET',0,190,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('RET','OTH',0,190,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('OIN','IND',0,180,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIN','OFF',0,180,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIN','MIX',0,180,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIN','RET',0,180,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OIN','OTH',0,180,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('OUT','IND',0,120,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OUT','OFF',0,120,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OUT','MIX',0,120,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OUT','RET',0,120,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OUT','OTH',0,120,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('ORM','IND',0,170,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ORM','OFF',0,170,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ORM','MIX',0,170,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ORM','RET',0,170,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('ORM','OTH',0,170,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('OPY','IND',0,110,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OPY','OFF',0,110,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OPY','MIX',0,110,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OPY','RET',0,110,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OPY','OTH',0,110,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('SC4','IND',0,150,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('SC4','OFF',0,150,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('SC4','MIX',0,150,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('SC4','RET',0,150,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('SC4','OTH',0,150,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('OMF','IND',0,90,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OMF','OFF',0,90,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OMF','MIX',0,90,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OMF','RET',0,90,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	
	('OMF','OTH',0,90,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('OGA','IND',0,100,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('OGA','OFF',0,100,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('OGA','MIX',0,100,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('OGA','RET',0,100,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('OGA','OTH',0,100,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('MLE','IND',0,200,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('MLE','OFF',0,200,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('MLE','MIX',0,200,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('MLE','RET',0,200,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('MLE','OTH',0,200,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('CRS','IND',0,210,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CRS','OFF',0,210,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CRS','MIX',0,210,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CRS','RET',0,210,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CRS','OTH',0,210,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('CEO','IND',0,220,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CEO','OFF',0,220,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CEO','MIX',0,220,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CEO','RET',0,220,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CEO','OTH',0,220,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('CTI','IND',0,230,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CTI','OFF',0,230,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CTI','MIX',0,230,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CTI','RET',0,230,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CTI','OTH',0,230,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),
	('CCO','IND',0,240,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CCO','OFF',0,240,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CCO','MIX',0,240,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CCO','RET',0,240,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN'),	('CCO','OTH',0,240,0,GETDATE(),'GNARAYAN',GETDATE(),'GNARAYAN')
GO


