USE CRE_ODS
GO

SELECT 
		DATA_EFFDATE	
		,PROP_NAME	
		,ORIG_LOAN_AMT --,CUSTOMER_COMMIT_AMT	
		,/*'CRE FannieMae' AS */ LOB_SUB_CATEGORY											-- LOB_SUB_CATEGORY in CADM retrieves CRE PERM & HCC - values that do not identify the portfolio on the basis of FNMA, PERM, or CONS
		,LOAN_APPROVER_DATE	
		,ORIGINATION_DATE
		,PROP_ADDRESS	
		,PROP_CITY	
		,PROP_STATE_CD	
		,PROP_TYPE	
		,PROP_ZIP_CD
		,INTEREST_TYPE_CD	
		,INTEREST_CALC_METHOD	
		,ORIG_AMORT_PERIOD_MONTHS	
		, DATEDIFF(mm, FIRST_PAYMENT_DATE, ORIG_MATURITY_DATE)+1 AS ORIG_TERM_MONTHS	-- ORIG_TERM_MONTHS in CADM retrieves NULL and hence computed this way
		,PAYMENT_FREQUENCY	
		,INTEREST_INDEX_CODE	
		,LIEN_POSITION	
		,ASSET_MANAGER	
		,LOANNBR	
		,INTEREST_MARGIN	
		,CURR_INT_RATE	
		,INTEREST_TYPE_CD	
		--,ARM_PRODUCT_TYPE
		,BORR_NAME
		,BORR_ADDRESS
		,BORR_CITY
		,BORR_STATE_CD
		,BORR_ZIP_CD
		,RELATIONSHIP_ID
	FROM HSB_HIST.STRATEGY_EXTRACT a
	WHERE 
		a.DATA_EFFDATE = (SELECT MAX(DATA_EFFDATE) FROM HSB_HIST.STRATEGY_EXTRACT) 
		--AND a.FNMA_TIER =  ''
		--AND LOANNBR IN (900102637, 900101339)
		--AND PROP_NAME LIKE '%laurel park%'
	ORDER BY ORIGINATION_DATE DESC, LOANNBR


	
	--SELECT * FROM HSB_HIST.STRATEGY_EXTRACT WHERE FNMA_TIER <> '' AND DATA_EFFDATE = (SELECT MAX(DATA_EFFDATE) FROM HSB_HIST.STRATEGY_EXTRACT) 

	--SELECT DISTINCT LOB_SUB_CATEGORY FROM HSB_HIST.STRATEGY_EXTRACT