/*

SQL retrieves CADM data and juxtaposes with Backshop data based on 900* or 600* loan number

*/ 

USE CRE_ODS
GO

DECLARE @ASSET_MANAGER NVARCHAR (200)
DECLARE @COMP_BY_ADDRESS BIT

SET @ASSET_MANAGER = 'PHILLIP MROZ'
SET @COMP_BY_ADDRESS = 1

IF @COMP_BY_ADDRESS = 0 
BEGIN
	SELECT 
			b.ControlId AS [BS_IDENTIFIER]
			,d.ServicerLoanNumber AS [BACKSHOP_LOAN_NUMBER] ,a.LOANNBR AS [CADM_LOAN_NUMBER]
			, c.OrigLoanAmount AS [BACKSHOP_LOAN_AMOUNT] , a.ORIG_LOAN_AMT AS [CADM_LOAN_AMOUNT]
			,e.PropertyName AS [BACKSHOP_PROP_NAME] ,a.PROP_NAME AS [CADM_PROP_NAME]	
			,e.PropertyTypeMajorCd_F AS [BACKSHOP_PROP_TYPE]
			,e.StreetAddress AS [BACKSHOP_PROP_ADDRESS] ,a.PROP_ADDRESS	AS [CADM_PROP_ADDRESS]
			, e.City AS [BACKSHOP_PROP_CITY] ,a.PROP_CITY AS [CADM_PROP_CITY]
			, e.State AS [BACKSHOP_PROP_STATE],a.PROP_STATE_CD AS [CADM_PROP_STATE]
			, e.ZipCode AS [BACKSHOP_PROP_ZIP], a.PROP_ZIP_CD AS [CADM_PROP_ZIP]	
			,ASSET_MANAGER	
			,CONCAT(g.LastNameOrOrgName, SPACE(1), g.LastNameOrOrgNameContinued, SPACE(1), g.FirstName) AS [BACKSHOP_BORR_NAME] ,a.BORR_NAME AS [CADM_BORR_NAME]
			,CONCAT(g.StreetAddress, SPACE(1), g.StreetAddress2, SPACE(1), g.StreetAddress3, SPACE(1), g.StreetAddress4, SPACE(1)) AS [BACKSHOP_BORR_ADDRESS]  ,a.BORR_ADDRESS AS [CADM_BORR_ADDRESS]
			,g.City AS [BACKSHOP_BORR_CITY] ,a.BORR_CITY AS [CADM_BORR_CITY]
			,g.State AS [BACKSHOP_BORR_STATE] ,a.BORR_STATE_CD AS [CADM_BORR_STATE]
			,g.Zip AS [BACKSHOP_BORR_ZIP] ,a.BORR_ZIP_CD AS [CADM_BORR_ZIP]
			,g.BorrowerIDNumber AS [BACKSHOP_RELATIONSHIP_ID] ,a.RELATIONSHIP_ID AS [CADM_RELATIONSHIP_ID]
			,b.AuditAddUserId AS [CW]
		FROM HSB_HIST.STRATEGY_EXTRACT a
			LEFT JOIN (dbo.tblControlMaster b 
					INNER JOIN tblNote c ON b.ControlId = c.ControlId_F 
					LEFT JOIN tblNoteExp d ON d.NoteId_F = c.NoteId
					INNER JOIN tblProperty e ON e.ControlId_F = b.ControlId
					LEFT JOIN tblBorrowerOwnershipHierarchy f ON f.NoteId_F = c.NoteId AND f.ChildBorrowerId_F IS NULL 
					LEFT JOIN tblBorrower g ON g.BorrowerId = f.ParentBorrowerId_F
			) ON LTRIM(RTRIM(a.LOANNBR)) = RTRIM(LTRIM(d.servicerLoanNumber))
		WHERE 
			a.DATA_EFFDATE = (SELECT MAX(DATA_EFFDATE) FROM HSB_HIST.STRATEGY_EXTRACT) 
			--AND a.FNMA_TIER <> ''
			AND a.ASSET_MANAGER IN (@ASSET_MANAGER)
			--AND a.LOANNBR IN (900102637, 900101339)
		ORDER BY LOANNBR
END
ELSE
BEGIN 
	SELECT 
			b.ControlId AS [BS_IDENTIFIER]
			,d.ServicerLoanNumber AS [BACKSHOP_LOAN_NUMBER] ,a.LOANNBR AS [CADM_LOAN_NUMBER]
			, c.OrigLoanAmount AS [BACKSHOP_LOAN_AMOUNT] ,a.ORIG_LOAN_AMT AS [CADM_LOAN_AMOUNT]
			,e.PropertyTypeMajorCd_F AS [BACKSHOP_PROP_TYPE]
			,e.PropertyName AS [BACKSHOP_PROP_NAME] ,a.PROP_NAME AS [CADM_PROP_NAME]	
			,e.StreetAddress AS [BACKSHOP_PROP_ADDRESS] ,a.PROP_ADDRESS	AS [CADM_PROP_ADDRESS]
			, e.City AS [BACKSHOP_PROP_CITY] ,a.PROP_CITY AS [CADM_PROP_CITY]
			, e.State AS [BACKSHOP_PROP_STATE],a.PROP_STATE_CD AS [CADM_PROP_STATE]
			, e.ZipCode AS [BACKSHOP_PROP_ZIP], a.PROP_ZIP_CD AS [CADM_PROP_ZIP]
			,ASSET_MANAGER		
			,CONCAT(g.LastNameOrOrgName, SPACE(1), g.LastNameOrOrgNameContinued, SPACE(1), g.FirstName) AS [BACKSHOP_BORR_NAME] ,a.BORR_NAME AS [CADM_BORR_NAME]
			,CONCAT(g.StreetAddress, SPACE(1), g.StreetAddress2, SPACE(1), g.StreetAddress3, SPACE(1), g.StreetAddress4, SPACE(1)) AS [BACKSHOP_BORR_ADDRESS]  ,a.BORR_ADDRESS AS [CADM_BORR_ADDRESS]
			,g.City AS [BACKSHOP_BORR_CITY] ,a.BORR_CITY AS [CADM_BORR_CITY]
			,g.State AS [BACKSHOP_BORR_STATE] ,a.BORR_STATE_CD AS [CADM_BORR_STATE]
			,g.Zip AS [BACKSHOP_BORR_ZIP] ,a.BORR_ZIP_CD AS [CADM_BORR_ZIP]
			,g.BorrowerIDNumber AS [BACKSHOP_RELATIONSHIP_ID] ,a.RELATIONSHIP_ID AS [CADM_RELATIONSHIP_ID]
			,b.AuditAddUserId AS [CW]
		FROM HSB_HIST.STRATEGY_EXTRACT a
			LEFT JOIN (dbo.tblControlMaster b 
					INNER JOIN tblNote c ON b.ControlId = c.ControlId_F 
					LEFT JOIN tblNoteExp d ON d.NoteId_F = c.NoteId
					INNER JOIN tblProperty e ON e.ControlId_F = b.ControlId
					LEFT JOIN tblBorrowerOwnershipHierarchy f ON f.NoteId_F = c.NoteId AND f.ChildBorrowerId_F IS NULL 
					LEFT JOIN tblBorrower g ON g.BorrowerId = f.ParentBorrowerId_F
			) ON REPLACE(UPPER(LTRIM(RTRIM(CONCAT(LTRIM(RTRIM(e.StreetAddress)), SPACE(1), LTRIM(RTRIM(e.City)), SPACE(1), LTRIM(RTRIM(e.State)), SPACE(1), LTRIM(RTRIM(e.ZipCode)))))), ',', '') = REPLACE(UPPER(RTRIM(LTRIM(CONCAT(LTRIM(RTRIM(a.PROP_ADDRESS)), SPACE(1), LTRIM(RTRIM(a.PROP_CITY)), SPACE(1), LTRIM(RTRIM(a.PROP_STATE_CD)), SPACE(1), LTRIM(RTRIM(a.PROP_ZIP_CD)))))), ',', '')
		WHERE 
			a.DATA_EFFDATE = (SELECT MAX(DATA_EFFDATE) FROM HSB_HIST.STRATEGY_EXTRACT) 
			--AND a.FNMA_TIER <> ''
			AND a.ASSET_MANAGER IN (@ASSET_MANAGER)
			--AND a.LOANNBR IN (900102637, 900101339)
		ORDER BY LOANNBR
END