USE CRE_ODS 
GO


-- COMMENT SECTION IN SSRS -- BEGIN
DECLARE @ServicerLoanNumber BIGINT
DECLARE @Statement NVARCHAR (100)
SET @ServicerLoanNumber = 	600101608
SET @Statement = '1/17-9/17 Year to Da'
-- COMMENT SECTION IN SSRS -- END

DECLARE @ControlId NVARCHAR (7)

SELECT @ControlId = ControlId_F FROM tblNote INNER JOIN tblNoteExp ON NoteId = NoteId_F WHERE ServicerLoanNumber = @ServicerLoanNumber

-- THIS IS A PROBLEM IF THE RATE HAD RECENTLY CHANGED AND/OR THE LOAN CHANGED FROM IO TO P&I RATE

;WITH payments AS (
	SELECT TOP 30 
		[DATA_EFFDATE], 
		[PAYMENT-P&I_AMT] = CASE PAYMENT_FREQUENCY
			WHEN 'Semi-Monthly' THEN [PAYMENT-P&I_AMT] * 2 
			WHEN 'Monthly' THEN [PAYMENT-P&I_AMT] * 12
		END, 
		[PAYMENT-RES_AMT] = CASE PAYMENT_FREQUENCY
			WHEN 'Semi-Monthly' THEN [PAYMENT-RES_AMT] * 2 
			WHEN 'Monthly' THEN [PAYMENT-RES_AMT] * 12
		END, 
		[PAYMENT-T&I_AMT] = CASE PAYMENT_FREQUENCY
			WHEN 'Semi-Monthly' THEN [PAYMENT-T&I_AMT] * 2 
			WHEN 'Monthly' THEN [PAYMENT-T&I_AMT] * 12
		END,
		[PAYMENT-TOTAL_AMT] = CASE PAYMENT_FREQUENCY
			WHEN 'Semi-Monthly' THEN [PAYMENT-TOTAL_AMT] * 2 
			WHEN 'Monthly' THEN [PAYMENT-TOTAL_AMT]* 12
		END,
		LOANNBR  FROM HSB_HIST.STRATEGY_EXTRACT WHERE LOANNBR = @ServicerLoanNumber AND [PAYMENT-P&I_AMT] > 0 AND [PAYMENT-TOTAL_AMT] > 0 -- ORDER BY DATA_EFFDATE DESC
	)

SELECT TOP 1 OpStatementHeaderId, StatementDate, MonthsCovered, StatementYear, NetOpInc, NetCashFlow, [DATA_EFFDATE], [PAYMENT-P&I_AMT], [PAYMENT-RES_AMT], [PAYMENT-T&I_AMT], [PAYMENT-TOTAL_AMT], LOANNBR  FROM (tblOpStatementHeader 
	INNER JOIN tblOperatingStatementBlueLineCalc ON OpStatementHeaderId = OpStatementHeaderId_F) CROSS JOIN payments 
WHERE StatementYear IN (@Statement) AND PropertyId_F IN (SELECT PropertyId FROM tblProperty WHERE ControlId_F = @ControlId) 
ORDER BY DATA_EFFDATE DESC




-- SQL to get list of loans with their month-end end generated in CADM
/*

SELECT LOANNBR, /*DATA_EFFDATE AS [AS-OF-DATE],*/ SUM([PAYMENT-P&I_AMT]) AS [2018_ANN_DS_AMT] /*[MONTHLY_PAYMENT], PAYMENT_TYPE, PAYMENT_FREQUENCY*/ FROM HSB_HIST.STRATEGY_EXTRACT WHERE  DATA_EFFDATE IN (
'2018-01-31',
'2018-02-28',
'2018-03-31',
'2018-04-30',
'2018-05-31',
'2018-06-30',
'2018-07-31',
'2018-08-31',
'2018-09-30',
'2018-10-31',
'2018-11-30',
'2018-12-31'
) 
GROUP BY LOANNBR
ORDER BY CONVERT(INT, LOANNBR) --, DATA_EFFDATE


*/


